/**
 * @file Coordinates adapter processing and mutation scheduling across a document's lifecycle.
 */

import {
    DocumentMutationScheduler,
    type AffectedMutationBatch,
} from "./document-mutation-scheduler";
import {
    reconcileDocumentRegion,
    reconcileDocumentSources,
    processDocument,
    type DocumentDiagnosticSink,
    type ProcessInput,
} from "./process-document";
import {
    capturePageOwnedTextChange,
    getOwnedSourceForOutput,
    getOwnedTimestampSourceEntries,
    readPageOwnedText,
    restoreTimestampPresentations,
} from "./render-timestamp-presentation";
import { DIAGNOSTIC_CATEGORY } from "../../shared/diagnostics/contracts";
import { defaultRegistry } from "../adapters/registry";
import type {
    TimestampExtractionContext,
    TimestampSourceAttribute,
} from "../adapters/types";

/**
 * Confirms that an element still belongs to the controller's document before it is reformatted.
 *
 * @param element - Candidate element retained from an earlier pass.
 * @param document - Document the controller currently owns.
 * @returns - Whether the element remains connected to that document.
 */
function isConnectedToDocument(element: Element, document: Document): boolean {
    return element.ownerDocument === document && element.isConnected;
}

/**
 * Suppresses a duplicate root when a broader root already covers the same candidate element.
 *
 * @param roots - Broader roots already selected for processing.
 * @param element - Candidate element to test for coverage.
 * @returns - Whether an existing root already contains the element.
 */
function coveredBy(roots: readonly Element[], element: Element): boolean {
    return roots.some((root) => root.contains(element));
}

/**
 * Owns the active document pass, mutation scheduler, and restoration lifecycle for one page.
 *
 */
export class DocumentTransformationController {
    /**
     * Distinguishes an inactive controller from one that currently owns document transformations.
     */
    private phase: "idle" | "active" = "idle";

    /**
     * Generated time nodes from the latest full pass, retained for targeted reconciliation.
     */
    private outputs: readonly HTMLTimeElement[] = [];

    /**
     * Mutation observer coordinator created on start and disposed during teardown.
     */
    private scheduler: DocumentMutationScheduler | undefined;

    /**
     * Current bounded diagnostic reporter, which callers may replace without restarting the
     * controller.
     */
    private diagnosticSink: DocumentDiagnosticSink | undefined;

    /**
     * Captures document-processing dependencies and seeds the current diagnostic sink before
     * activation.
     *
     * @param input - Document, adapter, presentation, and observer dependencies.
     */
    constructor(private readonly input: ProcessInput) {
        this.diagnosticSink = input.diagnosticSink;
    }

    /**
     * Replaces the optional diagnostic sink used by later processing and reconciliation passes.
     *
     * @param sink - Diagnostic event sink, or undefined to stop forwarding.
     */
    setDiagnosticSink(sink: DocumentDiagnosticSink | undefined): void {
        this.diagnosticSink = sink;
        const mutableInput = this.input as { diagnosticSink?: DocumentDiagnosticSink };
        if (sink) {
            mutableInput.diagnosticSink = sink;
        } else {
            Reflect.deleteProperty(mutableInput, "diagnosticSink");
        }
    }

    /**
     * Starts mutation scheduling and performs the initial document pass.
     *
     * @returns - Outputs generated by the initial document pass.
     */
    start(): readonly HTMLTimeElement[] {
        if (this.phase === "active") {
            return this.outputs;
        }

        const rules = (this.input.registry ?? defaultRegistry).matching(this.input.url);
        const extractionContext: TimestampExtractionContext = {
            url: this.input.url,
            readPageText: readPageOwnedText,
        };
        const sourceAttributes = [
            ...new Set(rules.flatMap((rule) => rule.mutationAttributes)),
        ];
        const scheduler = new DocumentMutationScheduler({
            document: this.input.root,
            getOwnedSourceForOutput,
            capturePageOwnedTextChange,
            sourceAttributes,
            getSourceMutationRoots: (element, attributeName, oldValue, wasTracked) => {
                const applicableRules = attributeName
                    ? rules.filter((rule) =>
                        rule.mutationAttributes.some(
                            (attribute) => attribute === attributeName,
                        ))
                    : rules;
                const ownedSources = new Set(
                    getOwnedTimestampSourceEntries(this.input.root)
                        .map(({ source }) => source),
                );
                const sources: Element[] = [];
                const seen = new Set<Element>();
                const addSource = (source: Element): void => {
                    if (!seen.has(source)) {
                        seen.add(source);
                        sources.push(source);
                    }
                };

                if (attributeName) {
                    let current: Element | null = element;
                    while (current && current.ownerDocument === this.input.root) {
                        if (ownedSources.has(current)) {
                            addSource(current);
                            break;
                        }
                        current = current.parentElement;
                    }
                    for (const rule of applicableRules) {
                        if (rule.getMutationSources) {
                            for (const source of rule.getMutationSources(
                                element,
                                attributeName as TimestampSourceAttribute,
                                oldValue ?? null,
                            )) {
                                addSource(source);
                            }
                            continue;
                        }
                        const shouldInspect = rule.shouldInspectMutation?.(
                            element,
                            attributeName,
                            extractionContext,
                        ) ?? true;
                        if (!shouldInspect) {
                            continue;
                        }
                        current = element;
                        while (current && current.ownerDocument === this.input.root) {
                            if (rule.matchesElement(current, extractionContext)) {
                                addSource(current);
                                break;
                            }
                            current = current.parentElement;
                        }
                    }
                    if (sources.length === 0 && wasTracked) {
                        addSource(element);
                    }
                    return sources;
                }

                const inspectionRules = applicableRules.filter((rule) =>
                    rule.shouldInspectMutation?.(
                        element,
                        undefined,
                        extractionContext,
                    ) ?? true
                );
                let current: Element | null = element;
                while (current && current.ownerDocument === this.input.root) {
                    if (ownedSources.has(current)) {
                        addSource(current);
                    }
                    const isMatching = inspectionRules.some(
                        (rule) => rule.matchesElement(
                            current as Element,
                            extractionContext,
                        ),
                    );
                    if (isMatching) {
                        addSource(current);
                    }
                    current = current.parentElement;
                }
                return sources;
            },
            onBatch: (batch) => {
                if (
                    this.diagnosticSink
                    && (
                        batch.sourceTargets.length > 0
                        || batch.visibilityRoots.length > 0
                        || batch.displacedOutputSources.length > 0
                    )
                ) {
                    this.diagnosticSink({
                        category: DIAGNOSTIC_CATEGORY.MUTATION,
                        count:
                            batch.sourceTargets.length +
                            batch.visibilityRoots.length +
                            batch.displacedOutputSources.length,
                    });
                }
                this.reconcile(batch, scheduler);
            },
        });
        this.scheduler = scheduler;
        try {
            scheduler.start();
            this.outputs = processDocument({ ...this.input, ownedDomMutations: scheduler });
            this.phase = "active";
            return this.outputs;
        } catch (error) {
            scheduler.stop();
            restoreTimestampPresentations(this.input.root);
            this.outputs = [];
            this.scheduler = undefined;
            this.phase = "idle";
            throw error;
        }
    }

    /**
     * Stops observation and restores the document to its pre-rendered state.
     */
    teardown(): void {
        this.scheduler?.stop();
        this.scheduler = undefined;
        restoreTimestampPresentations(this.input.root);
        this.outputs = [];
        this.phase = "idle";
    }

    /**
     * Reformat only already owned, connected sources after a presentation save.
     *
     * @returns The time elements updated during the reformat operation.
     */
    reformatOwned(): readonly HTMLTimeElement[] {
        if (this.phase !== "active") {
            return this.outputs;
        }
        const scheduler = this.scheduler;
        if (!scheduler) {
            return this.outputs;
        }
        const sources = getOwnedTimestampSourceEntries(this.input.root)
            .map(({ source }) => source)
            .filter((source) => isConnectedToDocument(source, this.input.root));
        this.outputs = reconcileDocumentSources({
            ...this.input,
            sources,
            ownedDomMutations: scheduler,
        });
        return this.outputs;
    }

    /**
     * Applies a settings change only to affected connected source elements.
     *
     * @param batch - Connected sources and display settings to reapply.
     * @param scheduler - Mutation scheduler coordinating owned DOM changes.
     */
    private reconcile(batch: AffectedMutationBatch, scheduler: DocumentMutationScheduler): void {
        const removedRoots = batch.removedRoots.filter(
            (root) => !isConnectedToDocument(root, this.input.root),
        );
        if (removedRoots.length > 0) {
            restoreTimestampPresentations(removedRoots, scheduler);
        }

        for (const root of batch.addedRoots) {
            if (isConnectedToDocument(root, this.input.root)) {
                reconcileDocumentRegion({ ...this.input, root, ownedDomMutations: scheduler });
            }
        }

        const sourceTargets = batch.sourceTargets.filter(
            (target) =>
                isConnectedToDocument(target, this.input.root)
                && !coveredBy(batch.addedRoots, target)
                && !coveredBy(batch.visibilityRoots, target),
        );
        if (sourceTargets.length > 0) {
            reconcileDocumentSources({
                ...this.input,
                sources: sourceTargets,
                ownedDomMutations: scheduler,
            });
        }

        for (const root of batch.visibilityRoots) {
            if (
                isConnectedToDocument(root, this.input.root) &&
                !coveredBy(batch.addedRoots, root)
            ) {
                reconcileDocumentRegion({
                    ...this.input,
                    root,
                    ownedDomMutations: scheduler,
                });
            }
        }

        for (const source of batch.displacedOutputSources) {
            if (
                isConnectedToDocument(source, this.input.root) &&
                !coveredBy(batch.addedRoots, source) &&
                !batch.sourceTargets.includes(source) &&
                !coveredBy(batch.visibilityRoots, source)
            ) {
                reconcileDocumentRegion({
                    ...this.input,
                    root: source,
                    ownedDomMutations: scheduler,
                });
            }
        }
    }
}
