/**
 * @file Coordinates adapter processing and mutation scheduling across a document's lifecycle.
 */

import {
    DocumentMutationScheduler,
    type AffectedMutationBatch,
} from "./document-mutation-scheduler";
import {
    reconcileDocumentRegion,
    processDocument,
    type DocumentDiagnosticSink,
    type ProcessInput,
} from "./process-document";
import {
    getOwnedSourceEntries,
    getOwnedSourceForOutput,
    restoreExactTimes,
} from "./render-exact-time";
import { DIAGNOSTIC_CATEGORY } from "../../shared/diagnostics/contracts";

/**
 * Confirms that an element still belongs to the controller's document before it is reformatted.
 *
 * @param element - Candidate element retained from an earlier pass.
 * @param document - Document the controller currently owns.
 * @returns - Whether the element remains connected to that document.
 */
function isConnectedToDocument(element: Element, document: Document): boolean {
    return element.ownerDocument === document && element.isConnected;
}

/**
 * Suppresses a duplicate root when a broader root already covers the same candidate element.
 *
 * @param roots - Broader roots already selected for processing.
 * @param element - Candidate element to test for coverage.
 * @returns - Whether an existing root already contains the element.
 */
function coveredBy(roots: readonly Element[], element: Element): boolean {
    return roots.some((root) => root.contains(element));
}

/**
 * Owns the active document pass, mutation scheduler, and restoration lifecycle for one page.
 *
 */
export class DocumentTransformationController {
    /**
     * Distinguishes an inactive controller from one that currently owns document transformations.
     */
    private phase: "idle" | "active" = "idle";

    /**
     * Generated time nodes from the latest full pass, retained for targeted reconciliation.
     */
    private outputs: readonly HTMLTimeElement[] = [];

    /**
     * Mutation observer coordinator created on start and disposed during teardown.
     */
    private scheduler: DocumentMutationScheduler | undefined;

    /**
     * Current bounded diagnostic reporter, which callers may replace without restarting the
     * controller.
     */
    private diagnosticSink: DocumentDiagnosticSink | undefined;

    /**
     * Captures document-processing dependencies and seeds the current diagnostic sink before
     * activation.
     *
     * @param input - Document, adapter, presentation, and observer dependencies.
     */
    constructor(private readonly input: ProcessInput) {
        this.diagnosticSink = input.diagnosticSink;
    }

    /**
     * Replaces the optional diagnostic sink used by later processing and reconciliation passes.
     *
     * @param sink - Diagnostic event sink, or undefined to stop forwarding.
     */
    setDiagnosticSink(sink: DocumentDiagnosticSink | undefined): void {
        this.diagnosticSink = sink;
        const mutableInput = this.input as { diagnosticSink?: DocumentDiagnosticSink };
        if (sink) {
            mutableInput.diagnosticSink = sink;
        } else {
            Reflect.deleteProperty(mutableInput, "diagnosticSink");
        }
    }

    /**
     * Starts mutation scheduling and performs the initial document pass.
     *
     * @returns - Outputs generated by the initial document pass.
     */
    start(): readonly HTMLTimeElement[] {
        if (this.phase === "active") {
            return this.outputs;
        }

        const scheduler = new DocumentMutationScheduler({
            document: this.input.root,
            getOwnedSourceForOutput,
            onBatch: (batch) => {
                if (this.diagnosticSink) {
                    this.diagnosticSink({
                        category: DIAGNOSTIC_CATEGORY.MUTATION,
                        count:
                            batch.addedRoots.length +
                            batch.removedRoots.length +
                            batch.datetimeTargets.length +
                            batch.visibilityRoots.length +
                            batch.displacedOutputSources.length,
                    });
                }
                this.reconcile(batch, scheduler);
            },
        });
        this.scheduler = scheduler;
        try {
            scheduler.start();
            this.outputs = processDocument({ ...this.input, ownedDomMutations: scheduler });
            this.phase = "active";
            return this.outputs;
        } catch (error) {
            scheduler.stop();
            restoreExactTimes(this.input.root);
            this.outputs = [];
            this.scheduler = undefined;
            this.phase = "idle";
            throw error;
        }
    }

    /**
     * Stops observation and restores the document to its pre-rendered state.
     */
    teardown(): void {
        this.scheduler?.stop();
        this.scheduler = undefined;
        restoreExactTimes(this.input.root);
        this.outputs = [];
        this.phase = "idle";
    }

    /**
     * Reformat only already owned, connected sources after a presentation save.
     *
     * @returns The time elements updated during the reformat operation.
     */
    reformatOwned(): readonly HTMLTimeElement[] {
        if (this.phase !== "active") {
            return this.outputs;
        }
        const scheduler = this.scheduler;
        if (!scheduler) {
            return this.outputs;
        }
        const outputs: HTMLTimeElement[] = [];
        for (const { source } of getOwnedSourceEntries(this.input.root)) {
            if (!isConnectedToDocument(source, this.input.root)) {
                continue;
            }
            outputs.push(
                ...reconcileDocumentRegion({
                    ...this.input,
                    root: source,
                    ownedDomMutations: scheduler,
                }),
            );
        }
        this.outputs = outputs;
        return outputs;
    }

    /**
     * Applies a settings change only to affected connected source elements.
     *
     * @param batch - Connected sources and display settings to reapply.
     * @param scheduler - Mutation scheduler coordinating owned DOM changes.
     */
    private reconcile(batch: AffectedMutationBatch, scheduler: DocumentMutationScheduler): void {
        for (const root of batch.removedRoots) {
            if (!isConnectedToDocument(root, this.input.root)) {
                restoreExactTimes(root, scheduler);
            }
        }

        for (const root of batch.addedRoots) {
            if (isConnectedToDocument(root, this.input.root)) {
                reconcileDocumentRegion({ ...this.input, root, ownedDomMutations: scheduler });
            }
        }

        for (const target of batch.datetimeTargets) {
            if (
                isConnectedToDocument(target, this.input.root) &&
                !coveredBy(batch.addedRoots, target) &&
                !coveredBy(batch.visibilityRoots, target)
            ) {
                reconcileDocumentRegion({
                    ...this.input,
                    root: target,
                    ownedDomMutations: scheduler,
                });
            }
        }

        for (const root of batch.visibilityRoots) {
            if (
                isConnectedToDocument(root, this.input.root) &&
                !coveredBy(batch.addedRoots, root)
            ) {
                reconcileDocumentRegion({
                    ...this.input,
                    root,
                    ownedDomMutations: scheduler,
                });
            }
        }

        for (const source of batch.displacedOutputSources) {
            if (
                isConnectedToDocument(source, this.input.root) &&
                !coveredBy(batch.addedRoots, source) &&
                !batch.datetimeTargets.includes(source) &&
                !coveredBy(batch.visibilityRoots, source)
            ) {
                reconcileDocumentRegion({
                    ...this.input,
                    root: source,
                    ownedDomMutations: scheduler,
                });
            }
        }
    }
}
