/**
 * @file Verifies locale-aware relative-presentation classification.
 */

import { describe, expect, it } from "vitest";

import {
    CANONICAL_RELATIVE_TIME_LOCALES,
    RELATIVE_PRESENTATION_PROFILE,
    isRelativeLabelText,
} from "../../../../src/content-script/adapters/relative-presentation";

const CANONICAL = [
    "ar", "bg", "ca", "cs", "da", "de", "el", "en", "es", "es-419",
    "fa", "fi", "fil", "fr", "he", "hi", "hr", "hu", "id", "it",
    "ja", "ko", "lt", "nb", "nl", "pl", "pt-BR", "pt-PT", "ro", "ru",
    "sk", "sl", "sr", "sv", "th", "tr", "uk", "vi", "zh-CN", "zh-TW",
] as const;

const ABSOLUTE_DATE_FIELDS = [
    { name: "weekday", values: ["long", "short", "narrow"] },
    { name: "era", values: ["long", "short", "narrow"] },
    { name: "year", values: ["numeric", "2-digit"] },
    { name: "month", values: ["numeric", "2-digit", "long", "short", "narrow"] },
    { name: "day", values: ["numeric", "2-digit"] },
] as const;
const ABSOLUTE_TIME_FIELDS = [
    { name: "hour", values: ["numeric", "2-digit"] },
    { name: "minute", values: ["numeric", "2-digit"] },
    { name: "second", values: ["numeric", "2-digit"] },
    { name: "dayPeriod", values: ["long", "short", "narrow"] },
    {
        name: "timeZoneName",
        values: [
            "short", "long", "shortOffset", "longOffset", "shortGeneric", "longGeneric",
        ],
    },
] as const;
const TEST_DEFAULT_IGNORABLES = /[\p{Cf}\u034f]/gu;
const TEST_NUMBER_SEQUENCE = /[\p{Number}]+/gu;

/**
 * Mirrors the documented presentation normalization for corpus prefiltering.
 *
 * Public classifier assertions remain the source of truth for every collision.
 *
 * @param value - Absolute or compact label generated by Intl.
 * @returns - Comparison signature used only to skip non-colliding corpus entries.
 */
function presentationSignature(value: string): string {
    return value.normalize("NFKC")
        .replace(TEST_DEFAULT_IGNORABLES, "")
        .trim()
        .replace(/\s+/gu, " ")
        .toLowerCase()
        .replace(TEST_NUMBER_SEQUENCE, "{number}");
}

/**
 * Builds every one- and two-field absolute formatting option from one field corpus.
 *
 * @param fields - Intl field names and their admitted display values.
 * @returns - Validatable option candidates; unsupported combinations are skipped by callers.
 */
function absoluteFieldOptions(
    fields: readonly {
        readonly name: string;
        readonly values: readonly string[];
    }[],
): readonly Intl.DateTimeFormatOptions[] {
    const options: Intl.DateTimeFormatOptions[] = [];
    for (const [index, field] of fields.entries()) {
        for (const value of field.values) {
            options.push({ [field.name]: value });
        }
        for (const other of fields.slice(index + 1)) {
            for (const value of field.values) {
                for (const otherValue of other.values) {
                    options.push({
                        [field.name]: value,
                        [other.name]: otherValue,
                    });
                }
            }
        }
    }
    return options;
}

/**
 * Selects dates covering every month and weekday arrangement used by narrow fields.
 *
 * @returns - Bounded representative absolute-date corpus.
 */
function absoluteDateSamples(): readonly Date[] {
    const dates: Date[] = [];
    for (let month = 0; month < 12; month += 1) {
        const weekdays = new Set<number>();
        for (let day = 1; day <= 31 && weekdays.size < 7; day += 1) {
            const date = new Date(Date.UTC(2024, month, day, 12, 8, 9));
            if (date.getUTCMonth() === month && !weekdays.has(date.getUTCDay())) {
                weekdays.add(date.getUTCDay());
                dates.push(date);
            }
        }
    }
    return dates;
}

/**
 * Generates every adapter-style compact template for the collision corpus.
 *
 * @param locale - Canonical locale whose compact forms are generated.
 * @returns - Localized compact number-unit templates across representative plurals.
 */
function compactPatterns(locale: string): readonly string[] {
    const patterns = new Set<string>();
    for (const unitDisplay of ["short", "narrow"] as const) {
        for (const unit of [
            "second", "minute", "hour", "day", "week", "month", "year",
        ] as const) {
            const formatter = new Intl.NumberFormat(locale, {
                style: "unit",
                unit,
                unitDisplay,
            });
            for (const value of [0, 1, 2, 5, 21, 2024]) {
                patterns.add(formatter.format(value));
            }
        }
    }
    return [...patterns];
}

/**
 * Creates one page label with an explicit inherited-language boundary.
 *
 * @param lang - BCP 47 language value placed on the label.
 * @returns - Connected label element used by the classifier.
 */
function source(lang: string): HTMLElement {
    const element = document.createElement("time");
    element.lang = lang;
    document.body.append(element);
    return element;
}

describe("relative presentation classification", () => {
    it("keeps the confirmed canonical locale set", () => {
        expect(CANONICAL_RELATIVE_TIME_LOCALES).toEqual(CANONICAL);
    });

    it.each(CANONICAL)("accepts generated relative text for %s", (locale) => {
        const label = new Intl.RelativeTimeFormat(locale, {
            numeric: "always",
            style: "long",
        }).format(-2, "hour");
        expect(isRelativeLabelText(label, source(locale), [], [
            RELATIVE_PRESENTATION_PROFILE.DIRECTIONAL,
        ])).toBe(true);
    });

    it.each(CANONICAL)("rejects an absolute date for %s", (locale) => {
        const label = new Intl.DateTimeFormat(locale, { dateStyle: "medium" })
            .format(new Date("2026-08-22T12:00:00Z"));
        expect(isRelativeLabelText(label, source(locale), [], [
            RELATIVE_PRESENTATION_PROFILE.DIRECTIONAL,
            RELATIVE_PRESENTATION_PROFILE.COMPACT_AGE,
        ])).toBe(false);
    });

    it.each(CANONICAL)("accepts an unambiguous compact localized age for %s", (locale) => {
        const element = source(locale);
        const units = [
            "second", "minute", "hour", "day", "week", "month", "year",
        ] as const;
        const labels = units.flatMap((unit) => ["short", "narrow"].map((unitDisplay) =>
            new Intl.NumberFormat(locale, {
                style: "unit",
                unit,
                unitDisplay: unitDisplay as "short" | "narrow",
            }).format(2)));
        expect(labels.some((label) => isRelativeLabelText(label, element, [], [
            RELATIVE_PRESENTATION_PROFILE.DIRECTIONAL,
            RELATIVE_PRESENTATION_PROFILE.COMPACT_AGE,
        ]))).toBe(true);
    });

    it.each(CANONICAL)("rejects unknown wording for %s", (locale) => {
        expect(isRelativeLabelText(`unsupported-${locale}`, source(locale), [], [
            RELATIVE_PRESENTATION_PROFILE.DIRECTIONAL,
            RELATIVE_PRESENTATION_PROFILE.COMPACT_AGE,
        ])).toBe(false);
    });

    it.each([
        ["bg", { year: "numeric" }],
        ["ko", { day: "numeric" }],
        ["zh-CN", { year: "numeric" }],
    ] as const)("rejects an ambiguous compact/absolute shape for %s", (
        locale,
        options,
    ) => {
        const label = new Intl.DateTimeFormat(locale, {
            ...options,
            timeZone: "UTC",
        }).format(new Date("2026-08-22T12:00:00Z"));
        expect(isRelativeLabelText(label, source(locale), [], [
            RELATIVE_PRESENTATION_PROFILE.DIRECTIONAL,
            RELATIVE_PRESENTATION_PROFILE.COMPACT_AGE,
        ])).toBe(false);
    });

    it.each([
        ["ro", "long"],
        ["sv", "short"],
    ] as const)("rejects a compact age that is also a calendar fragment for %s", (
        locale,
        weekday,
    ) => {
        const date = new Date("2026-02-02T12:00:00Z");
        const label = new Intl.DateTimeFormat(locale, {
            month: "numeric",
            weekday,
            timeZone: "UTC",
        }).format(date);
        expect(label).toBe(new Intl.NumberFormat(locale, {
            style: "unit",
            unit: "month",
            unitDisplay: "short",
        }).format(2));
        expect(isRelativeLabelText(label, source(locale), [], [
            RELATIVE_PRESENTATION_PROFILE.DIRECTIONAL,
            RELATIVE_PRESENTATION_PROFILE.COMPACT_AGE,
        ])).toBe(false);
    });

    it("rejects a two-digit Bulgarian day fragment that resembles a compact age", () => {
        const date = new Date("2024-12-01T12:00:00Z");
        const label = new Intl.DateTimeFormat("bg", {
            day: "2-digit",
            month: "narrow",
            timeZone: "UTC",
        }).format(date);
        expect(label).toBe(new Intl.NumberFormat("bg", {
            style: "unit",
            unit: "day",
            unitDisplay: "short",
        }).format(1));
        expect(isRelativeLabelText(label, source("bg"), [], [
            RELATIVE_PRESENTATION_PROFILE.COMPACT_AGE,
        ])).toBe(false);
    });

    it.each([
        ["nb", new Date("2024-01-01T12:00:00Z"), "month", "narrow"],
        ["sk", new Date("2024-01-06T12:00:00Z"), "second", "short"],
    ] as const)("rejects a narrow absolute collision for %s before adapter patterns", (
        locale,
        date,
        unit,
        unitDisplay,
    ) => {
        const label = new Intl.DateTimeFormat(locale, {
            year: "numeric",
            weekday: "narrow",
            timeZone: "UTC",
        }).format(date);
        const adapterPattern = new Intl.NumberFormat(locale, {
            style: "unit",
            unit,
            unitDisplay,
        }).format(1);
        expect(isRelativeLabelText(label, source(locale), [], [
            RELATIVE_PRESENTATION_PROFILE.COMPACT_AGE,
        ], [adapterPattern])).toBe(false);
    });

    it("rejects the complete bounded Intl absolute-fragment collision corpus", () => {
        const dateOptions = absoluteFieldOptions(ABSOLUTE_DATE_FIELDS);
        const timeOptions = absoluteFieldOptions(ABSOLUTE_TIME_FIELDS);
        const dates = absoluteDateSamples();
        const times = Array.from({ length: 24 }, (_, hour) =>
            new Date(Date.UTC(2024, 0, 1, hour, 8, 9)));
        for (const locale of CANONICAL) {
            const element = source(locale);
            const patterns = compactPatterns(locale);
            const compactSignatures = new Set(patterns.map(presentationSignature));
            const checkedLabels = new Set<string>();
            let acceptedAbsolute: string | null = null;
            for (const [options, samples] of [
                [dateOptions, dates],
                [timeOptions, times],
            ] as const) {
                for (const option of options) {
                    let formatter: Intl.DateTimeFormat;
                    try {
                        formatter = new Intl.DateTimeFormat(locale, {
                            ...option,
                            timeZone: "UTC",
                        });
                    } catch {
                        continue;
                    }
                    for (const date of samples) {
                        const label = formatter.format(date);
                        if (
                            !compactSignatures.has(presentationSignature(label))
                            || checkedLabels.has(label)
                        ) {
                            continue;
                        }
                        checkedLabels.add(label);
                        if (isRelativeLabelText(label, element, [], [
                            RELATIVE_PRESENTATION_PROFILE.COMPACT_AGE,
                        ], patterns)) {
                            acceptedAbsolute = `${locale}: ${label}`;
                            break;
                        }
                    }
                    if (acceptedAbsolute) {
                        break;
                    }
                }
                if (acceptedAbsolute) {
                    break;
                }
            }
            expect(acceptedAbsolute).toBeNull();
        }
    });

    it("rejects oversized page labels before normalization", () => {
        expect(isRelativeLabelText("2 hours ago".padEnd(513), source("en"), [], [
            RELATIVE_PRESENTATION_PROFILE.DIRECTIONAL,
        ])).toBe(false);
    });

    it("recognizes concrete Polish and Ukrainian examples", () => {
        expect(isRelativeLabelText("2 godz. temu", source("pl"), [], [
            RELATIVE_PRESENTATION_PROFILE.DIRECTIONAL,
        ])).toBe(true);
        expect(isRelativeLabelText("2 години тому", source("uk"), [], [
            RELATIVE_PRESENTATION_PROFILE.DIRECTIONAL,
        ])).toBe(true);
    });

    it.each([
        ["cs", -1.5, "hour"],
        ["pl", -1.5, "hour"],
        ["fr", -1_000_000, "year"],
    ] as const)("covers non-integer plural forms for %s", (locale, value, unit) => {
        const label = new Intl.RelativeTimeFormat(locale, {
            numeric: "always",
            style: "long",
        }).format(value, unit);
        expect(isRelativeLabelText(label, source(locale), [], [
            RELATIVE_PRESENTATION_PROFILE.DIRECTIONAL,
        ])).toBe(true);
    });

    it("allows bare units only for a compact age profile", () => {
        const element = source("en");
        expect(isRelativeLabelText("33w", element, [], [
            RELATIVE_PRESENTATION_PROFILE.DIRECTIONAL,
        ])).toBe(false);
        expect(isRelativeLabelText("33w", element, [], [
            RELATIVE_PRESENTATION_PROFILE.DIRECTIONAL,
            RELATIVE_PRESENTATION_PROFILE.COMPACT_AGE,
        ])).toBe(true);
    });

    it.each([
        "Aug 22, 2026",
        "16:08",
        "2 hrs",
        "2 3 hours ago",
        "unknown label",
    ])(
        "fails closed for %s",
        (label) => {
            expect(isRelativeLabelText(label, source("en"), [], [
                RELATIVE_PRESENTATION_PROFILE.DIRECTIONAL,
                RELATIVE_PRESENTATION_PROFILE.COMPACT_AGE,
            ])).toBe(false);
        },
    );

    it("does not override an empty or unsupported explicit language", () => {
        expect(isRelativeLabelText("2 hours ago", source(""), ["en-US"], [
            RELATIVE_PRESENTATION_PROFILE.DIRECTIONAL,
        ])).toBe(false);
        expect(isRelativeLabelText("2 hours ago", source("zz"), ["en-US"], [
            RELATIVE_PRESENTATION_PROFILE.DIRECTIONAL,
        ])).toBe(false);
    });

    it.each([
        ["en-US", "en"],
        ["es-MX", "es-419"],
        ["pt", "pt-PT"],
        ["zh-HK", "zh-TW"],
    ] as const)("normalizes %s into %s", (requested, canonical) => {
        const label = new Intl.RelativeTimeFormat(canonical, {
            numeric: "always",
            style: "long",
        }).format(-2, "hour");
        expect(isRelativeLabelText(label, source(requested), [], [
            RELATIVE_PRESENTATION_PROFILE.DIRECTIONAL,
        ])).toBe(true);
    });

    it("uses browser preferences only when the page declares no language", () => {
        const element = document.createElement("time");
        document.body.append(element);
        expect(isRelativeLabelText("2 hours ago", element, ["zz", "en-US"], [
            RELATIVE_PRESENTATION_PROFILE.DIRECTIONAL,
        ])).toBe(true);
    });

    it("fails closed for a nested language boundary inside one label", () => {
        const element = source("en");
        const nested = document.createElement("span");
        nested.lang = "pl";
        nested.textContent = "2 hours ago";
        element.append(nested);
        expect(isRelativeLabelText("2 hours ago", element, ["en-US"], [
            RELATIVE_PRESENTATION_PROFILE.DIRECTIONAL,
        ])).toBe(false);
    });
});
